functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без.
implicit:
  - Шрифт - хорошо виден, читаем без лишних усилий, цвет фона не должен совпадать с цветом шрифта, наполнение должно быть комфортно для просмотра
  - Пользователь не должен вносить изменения в описание, тем более в стоимость товара
  - Цена со скидкой должна отличаться визуально от стандартеой цены
  - Запретить одному пользователю просматривать данные другого пользователя
  
